# Generated by Django 2.2.7 on 2019-12-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='ParcelNum',
            field=models.ManyToManyField(to='track_module.SendRecieveInfo'),
        ),
    ]
