# Generated by Django 2.2.7 on 2019-12-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryman',
            old_name='ParcelNum',
            new_name='ParcelNums',
        ),
    ]
