# Generated by Django 2.2.7 on 2019-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='ManPhone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='Update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Reciever_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Reciever_addr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Reciever_phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Sender_Name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Sender_addr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Sender_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sendrecieveinfo',
            name='Sender_phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
